### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by nivong** [sjlu/popular-movies#1]
The website: http://movies.stevenlu.com/index.php/api gives an error:
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3

SELECT * FROM (`movies`) WHERE `tmdb_id` IN ()

Filename: /home/sjlu/public_html/movies.stevenlu.com/models/movies_model.php

Line Number: 44

**Comment by sjlu** [comment]
Ah yes, I need to refactor this entire thing in general. I'm sure the API's I've been using are way out of date.

**Comment by nivong** [comment]
If you need any help let me know!

**Comment by sjlu** [comment]
Haha, all help is welcome! Feel free to dive into my Node.js code

**Comment by sjlu** [comment]
Hey @nivong, I seem to have got it working great again. It'll produce an S3 file to the proper location.

**Comment by nivong** [comment]
Nice work @sjlu but the link returns a 404 haha

**Comment by sjlu** [comment]
Ah,

Was there any specific data that you were actually pulling from this
endpoint? I know it gave some extra data, but I removed it in favor of the
Amazon S3 cached response instead. In fact, the new popular-movies backend
does not even serve a endpoint, it just creates a .json file to Amazon S3

**Comment by nivong** [comment]
It was just the link, nothing special

**Comment by sjlu** [comment]
Gonna close this for now. You should use the JSON link since this no longer has a web server. All it does now is create a JSON file nightly as the incoming data tends not to change very often.
