### ISSUE TITLE
Filter by metacritic or rotten tomatoes

### ISSUE THREAD

**Issue by Bassir** [sjlu/popular-movies#10]
Any way to request a json for movies that meet a certain minimum RT, IMDB, or metacritic score?

**Comment by Bassir** [comment]
The best would be around 50. Whatever the threshold for “good” is, as I believe it is around 50 for Rotten Tomatoes. 

Best,

-Bassir

**Comment by Weavus** [comment]
Would be very interested in this as well but I'd advise not mixing RT/MC with IMDB ratings as they can be wildly different. I think it would be easier to use the Metacritic score as its already on the IMDB page of a movie and last time I checked RT removed their API support for grabbing scores.

I'd propose movies-critic-50.json, movies-critic-60.json, movies-critic-70.json, movies-critic-80.json and movies-imdb-50.json, movies-imdb-60.json, movies-imdb-70.json, movies-imdb-80.json 

Thanks for the great list BTW

**Comment by Bassir** [comment]
```
var filterByScore = function (movies) {
  return Promise.resolve(movies)
    .then(function (movies) {

      return _.filter(movies, function (movie) {
        return movie.metacritic_score >= 50.0
      })
    })
}

module.exports = function (cb) {
  return Promise.resolve(getMetacriticMovies())
    .bind({})
    .then(filterByReleaseDate)
    .then(filterByScore)
    .then(filterByValue('vote_count', 10))
    .then(filterByPopularity)
    .then(associateImdbIds)
    .then(uniqueMovies)
    .then(sanatizeForResponse)
    .nodeify(cb)
}
```

How's this?

**Comment by sjlu** [comment]
Very close. I decided to build it as a Class instead and cache the main file.

I've added in movies-metacritic-min50.json and movies-metacritic-min80.json to the mix. Check those out and let me know if those satisfy your needs.

More info on the README of this project.

**Comment by Bassir** [comment]
Perfect.

**Comment by sjlu** [comment]
I've also added IMDB & Rotten Tomatoes options too.
