### ISSUE TITLE
popular-series for TV shows?

### ISSUE THREAD

**Issue by gdob** [sjlu/popular-movies#12]
I know Sonarr doesn’t currently support lists like Radarr does, but it still would be useful to see which shows are the most popular using your algorithm instead of browsing IMDb or Trakt.

Could something like this be implemented?

**Comment by sjlu** [comment]
I don’t think it’ll work well unfortunately. This algorithm relies off of a score dependent on other scores at that time. TV shows don’t really have that kind of base.

For example. Movies only last in theaters for a set amount of time while TV shows can last forever (Netflix, Hulu, etc).

Sent via Superhuman iOS ( https://sprh.mn/?vip=tacticalazn@gmail.com )

**Comment by gdob** [comment]
Ah, that’s too bad. Would’ve been nice to have a curated list for new TV shows.

Thank you for the reply! :-)
