### ISSUE TITLE
Curious about the "better than most" criteria

### ISSUE THREAD

**Issue by AtariBaby** [sjlu/popular-movies#14]
Hi, I'm curious about the criteria "Rating greater than the general sentiment of movies currently out". What sites do you pull the rating from, and what rating number is the minimum?

I ask because I find that metacritic often gives a subpar rating to my beloved action movies (like many Marvel films) and frequently ranks movies high that were praised by critics but panned by audience. So your metacritic ratings lists (60,70,80,90) are likely to be a poor match for me. Conversely, I tend to take note of IMDB movies that score higher than 8, and I suspect a similar score on TMDB would be more aligned with movies I would like to catch.

**Comment by sjlu** [comment]
Hey @AtariBaby,

We pull from several sources, Metacritic being the seed for movies that we know about.

TMDB, RottenTomatoes, IMDB, and Metacritic are just some of them. Remember, the purpose of "popular-movies" is to understand if a movie is popular or not (e.g. funding, viewership, box office $, sentiment, etc) and is normally agnostic to ratings. The additional rating files are just filters on that. We can look into adding IMDB filters too if that's what you're looking for.

**Comment by yimingzhaomath** [comment]
if it's not too much trouble, IMDB filters are definitely a nice addition.

**Comment by sjlu** [comment]
@yimingzhaomath IMDB filters have been added 👍
