### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by tidusjar** [sjlu/popular-movies#3]
Hi, it seems that the JSON is no longer being populated?

**Comment by sjlu** [comment]
I have to fix this, give me some time - it's because a lot has changed with the services I use.

**Comment by tidusjar** [comment]
That's fine, I was not sure if you were aware of it!

**Comment by sjlu** [comment]
@tidusjar just fixed the issue

**Comment by tidusjar** [comment]
Thanks!
