### ISSUE TITLE
Currently no movies in list

### ISSUE THREAD

**Issue by Brandoskey** [sjlu/popular-movies#31]
As of 11/24/2021 the list is completely blank

**Comment by sjlu** [comment]
Hmm... ran locally so has to be something up with the cron with Heroku. I'll take a look into it over the weekend.

**Comment by WebAddict** [comment]
bump. Thanks Steven, we love your list service.

**Comment by sjlu** [comment]
@WebAddict I think it's good to go again - guessing it was because of the AWS outage yesterday
