### ISSUE TITLE
Radarr Error when using list

### ISSUE THREAD

**Issue by BrodyBuster** [sjlu/popular-movies#34]
Getting an error today in radarr when I enable this list … when I disable the list, error goes away. It looks like the json format is valid. 

https://s3.amazonawst.com/popular-movies/movies.json

Error:

Couldn't map movie to a movie on The Movie DB. It will not be added :(: Search for '' failed. Invalid response received from TMDb. |  
-- | --
  | 2:19pm | SkyHookProxy | System.InvalidOperationException: Sequence contains no elements at System.Linq.ThrowHelper.ThrowNoElementsException() at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 448: Sequence contains no elements

**Comment by sjlu** [comment]
@BrodyBuster Can you double check the URL? 

It needs to be:
https://s3.amazonaws.com/popular-movies/movies.json

**Comment by BrodyBuster** [comment]
Sorry. That was a typo on my part. The link in my original post is incorrect. I re-added the list to radarr using the custom StevenLu List, it loaded ok without the invalid response from tmdb. I will keep an eye on it to see if the error comes back. Thanks for the quick response.
