### ISSUE TITLE
Questionable recommendation

### ISSUE THREAD

**Issue by PieMistake** [sjlu/popular-movies#6]
As of now, your algorithm is suggesting "Just Getting Started" which is currently scoring 3.8/10 on IMDb, 5% on Rotten Tomatoes and 21/100 on Metacritic.

It's a great idea but I was wondering if such a stinker should be making that list?

**Comment by sjlu** [comment]
Yeah, you're right. I've updated it so it factors into a minimum vote count. This one got through even though it had zero votes.
