### ISSUE TITLE
Expand selection

### ISSUE THREAD

**Issue by JakeCow** [sjlu/popular-movies#8]
Hi,

Would it be possible to expand the movie list with even more popular movies? I'd love to be able to see top 20 most popular movies e.g. :)

Thank you for the great service!

**Comment by sjlu** [comment]
I could make it historical but this service tries its best to filter out the good from the bad based on data from several sources. 

I’ll keep it in mind.

**Comment by sjlu** [comment]
@JakeCow I've added in historical JSON files to the mix. Check out the README for more details.
